services:
  # Proxy
  reverse-proxy:
    image: nginx:alpine
    container_name: web-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./ssl/cloudflare/origin-cert.pem:/etc/nginx/ssl/origin-cert.pem:ro
      - ./ssl/cloudflare/origin-key.pem:/etc/nginx/ssl/origin-key.pem:ro
    depends_on:
      - portfolio
      - pixelquest
      - vikunja
      - chinese_notebook
    logging: &logging-config
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Portfolio
  portfolio:
    build: ./portfolio
    container_name: app-portfolio
    restart: always
    logging: *logging-config

  # PixelQuest
  pixelquest:
    build: ./pixel_quest
    container_name: app-pixelquest
    restart: always
    env_file:
      - ./secrets/pixel_quest.env
    logging: *logging-config

  # Manifeste Navigator
  manifeste:
    build: ./manifeste
    container_name: app-manifeste
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    logging: *logging-config

  miku:
    build: ./miku
    container_name: app-miku
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    logging: *logging-config

  # Vikunja (Task Manager)
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    restart: unless-stopped
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.aurelienb.com/
      VIKUNJA_SERVICE_SECRET: ad992a88961803bcdda68676ff06c6804795a7101955c688415a5df6b023c824
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    ports:
      - "3456:3456"
    volumes:
      - ./docker/vikunja/files:/app/vikunja/files
      - ./docker/vikunja/db:/db
    logging: *logging-config

  # Chinese Notebook (Hanzi First)
  chinese_notebook:
    build:
      context: ./chinese_notebook
      dockerfile: ../docker/chinese_notebook/Dockerfile
    container_name: app-chinese_notebook
    restart: always
    volumes:
      - ./docker/chinese_notebook/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    logging: *logging-config

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
